package pt.ulusofona.lp2.deisichess;

public class GameStaticData {
    public final static int BLACK_TEAM_ID = 10;
    public final static int WHITE_TEAM_ID = 20;
    public final static int KING_PIECE_ID = 1;
    public final static int KING_PIECE_VALUE = 1000;
    public final static String KING_NAME = "Rei";
    public final static int QUEEN_PIECE_ID = 2;
    public final static int QUEEN_PIECE_VALUE = 8;
    public final static String QUEEN_NAME = "Rainha";
    public final static int MAGIC_LITTLE_HORSE_PIECE_ID = 3;
    public final static int MAGIC_LITTLE_HORSE_PIECE_VALUE = 5;
    public final static String MAGIC_LITTLE_HORSE_NAME = "Ponei Mágico";
    public final static int VILLAGE_PRIEST_PIECE_ID = 4;
    public final static int VILLAGE_PRIEST_PIECE_VALUE = 3;
    public final static String VILLAGE_PRIEST_NAME = "Padre da Vila";
    public final static int HORIZONTAL_TOWER_PIECE_ID = 5;
    public final static int HORIZONTAL_TOWER_VALUE = 3;
    public final static String HORIZONTAL_TOWER_NAME = "TorreHor";
    public final static int VERTICAL_TOWER_PIECE_ID = 6;
    public final static int VERTICAL_TOWER_VALUE = 3;
    public final static String VERTICAL_TOWER_NAME = "TorreVert";
    public final static int HOMER_SIMPSON_PIECE_ID = 7;
    public final static int HOMER_SIMPSON_PIECE_VALUE = 2;
    public final static String HOMER_SIMPSON_NAME = "Homer Simpson";
    public final static int JOKER_PIECE_ID = 8;
    public final static int JOKER_PIECE_VALUE = 4;
    public final static String JOKER_NAME = "Joker";
    public final static String BLACK_TEAM_NAME = "Pretas";
    public final static String WHITE_TEAM_NAME = "Brancas";
    public final static String DEFEATED_LABEL = "capturado";
    public final static String NOT_DEFEATED_LABEL = "em jogo";
    public final static String NO_POSITION_LABEL = "n/a";
    public final static int TIE_RULE = 10;
    public final static String FILE_CONTENT_SEPARATOR = ":";
    public static String RESULT_TEAM_MESSAGE = "Equipa das ";
    public static String RESULT_GAME_TITLE = "JOGO DE CRAZY CHESS";
    public static String RESULT_LABEL_TITLE = "Resultado: ";
    public final static String RESULT_TIE_MESSAGE = "EMPATE";
    public final static String RESULT_WIN_MESSAGE = "VENCERAM AS ";
    public final static String KING_BLACK_TEAM = "king-0-team.png";
    public final static String KING_WHITE_TEAM = "king-1-team.png";
}
